version: 2

updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
    groups:
      non-major:
        update-types:
          - 'minor'
          - 'patch'
