#
# ATENÇÃO: Não apague esse arquivo
# Ele é usado pelo time do gb.tech para termos o catalogo dinâmico de aplicações
#

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: scafflater-template
  description: An Scafflater template to generate Scafflater templates
  tags:
    - scafflater
  annotations:
    github.com/project-slug: grupoboticario/scafflater-template
    github.com/team-slug: grupoboticario/alquimia
spec:
  type: service
  lifecycle: production
  owner: alquimia
  system: alquimia
  domain: platform-engineering
